import type { Metadata } from "next";
import { Inter, Red_Hat_Display } from "next/font/google";
import "./globals.css";
import TopBar from '@/components/top-bar/top-bar';
import React from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yachtways 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col h-screen`}>
      <TopBar/>
          <main className="flex-grow">{children}</main>
        <footer className="h-16 p-4 flex items-center shadow-md">Footer</footer>
      </body>
    </html>
  );
}
